services:
  - type: worker
    name: axel-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      BOT_TOKEN: "8437366478:AAHRskNg5XcAUn42ItkHlWz6nCh2UuvyOsw"
      ADMIN_CHAT_ID: "6933831183"
